#include <iostream>
#include <climits>
using namespace std;
int main()
{     
        cout<<sizeof(int)<<"\n";
        cout<<sizeof(int)<<"\n";
        cout<<sizeof(float)<<"\n";
        cout<<sizeof(short)<<"\n";
        cout<<sizeof(long)<<"\n";
        cout<<sizeof(long long)<<"\n";
        cout<<sizeof(char)<<"\n";
        cout<<sizeof(double)<<"\n";
        cout<<sizeof(long double)<<"\n";
        cout<<sizeof(long long)<<"\n";
        cout<<sizeof(long long)<<"\n";
        cout<<sizeof(long double)<<"\n";
        cout<<sizeof(long)<<"\n";
        cout<<sizeof(int)<<"\n";
        cout<<sizeof(float)<<"\n";
        return 0;
}        